# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set JAVA_HOME for Maven
        run: echo "export JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV

      - name: Set Maven to use Java 17
        run: |
          echo "export PATH=${JAVA_HOME}/bin:${PATH}" >> $GITHUB_ENV
          echo "Maven will now use Java 17"

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Print current directory
        run: pwd

      - name: List files in the current directory
        run: ls -l

  build:
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change to repository root directory
        run: cd $GITHUB_WORKSPACE

      - name: List files in the current directory
        run: ls -l

      - name: Print current directory
        run: pwd

      - name: Print Java version
        run: java -version

      - name: Set Java 17 for Maven
        run: mvn -N io.takari:maven:wrapper -Dmaven=3.8.8

      - name: Build with Maven
        run: ./mvnw --batch-mode -DskipTests package






        
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
      # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
